language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=anotherlocallib.settings.test
script:
- python manage.py test --settings=anotherlocallib.settings.test
- flake8 .
notifications:
  slack:
    secure: RU9H0rdV0+dy6Jh9zDgXFVgedlJtjYZx+lBUZX6RiEFNQlMTPYAVlvOmHRi7b/NKzk34TLaQrOcXKPvO1PFzecMOKtU0uBAukywJNqf8LUfQ1NxhS+m6uxBwhdFqXGs2HsKW6okECDmu16tlEvtGDgRFzB9beHXsHBVw3TUBH1H3BC+WPioI6+XsNl5gxT2xkgstMdQsCHx93r5+Js/9d157poDJIwfIXIDv46fzj7291nNqmNZ3R/yWOj6f6jFOFom1vFNqPvYp/CuPy+BWD9IRPkB/dPK0DfCntKusuGnjrxOMUkdlBCyku0N1fTyUMSlvbSs5VghjZmVp6b78EbYMM0zcso/Cq03tAQnkor6uUdbUMAHJGNEj9uZGekyhVlr6Jaf02qHHX1VYJCZD0QihpmbeqzT9JI7h/WNvkZ+7fCtShIyP45WUv9ccyANNkVikZoAYyVJsZodIDTrMSIXdWFHTXMbnZtG/s8rzgEeItZvhkxt0ORfVn4wLeDFH0tNTn8Kt/4dNbZspcsiQ6wNaXORScDoTn9WUT+i8myFCGhXv9ZE9HLPmeJPWUqWoswq3ZIewwbssC49rLI5iG5puAlA5b/v3mKiLrho8jB5oxMl4qjXr6tW9tiFkAvw3WQPI/uU+dx99JgG+8LhW+Nn1Y4+IcRIJouxc6DqmoMs=
deploy:
  provider: heroku
  api_key:
    secure: moiDjKkej+QBmFyvRO7AMad1BqyToTjHhykeqzSt83H2VckQF+RsGbX9cT7PvlW6CydO4usRNnMSMRJe/JrGkg8I0yLZGOxD+10Gwe3vxkdm2CHi5tue94ih+G3sQ7XSeKqpK2na8yWLc1V1tZTdag+2eRHZOk5GntrWhdyvzNp077QTVo73n60d9FnSM/qbckd7lSoVq2PL2X8plbTLZCXb4BM3lrC1vBkmC1fBQLV+M1X8MKCLB1w/VViMX8XHHRxft1QnUdvI5u+LF+H3lW0Az1e8487+vQet3bpC+rOvcl6FqOBQYrp85Mjq70XV82XanA+UHAbt80E5Z9Oky2jI10WmrcfQBMqYEu8w+UA5eUxa99gmrj09aMd/FMzL1xOw3CMmVhag24aeCdD2dAwiWbxkz5bwPInGI3vZWFu+ci32Wt4BPcux1sl6D6D+j4z/ZqoffMDmlPJUHhDzQGGPN50ejX4g0/nxBfJcLS7ARdhgzImDMIV+fd98mQp62f+1IsLnPnond1Lw+DPB6K4dZON8MuFpI+qsbzH4Q9EW4TYR9p47YgfPKzBXsyOMM3hyQfMVsGqr7wjybzqOFAOVBXU08wu2pFfo5Yapt7ku1pjCb2XML/NT2Jr1bDPC1Kpvjq1ZzCwiWvrFmKvcxpHZnihDFIOyYjS60LNZ2pU=
  app:
    master: anotherlocallib
    staging: anotherlocallib-staging
  on:
    repo: Nkoli/anotherlocallib
