language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate --settings=anotherlocallib.settings.test
script:
  - python manage.py test --settings=anotherlocallib.settings.test
  - flake8 .
notifications:
  slack:
    secure: RU9H0rdV0+dy6Jh9zDgXFVgedlJtjYZx+lBUZX6RiEFNQlMTPYAVlvOmHRi7b/NKzk34TLaQrOcXKPvO1PFzecMOKtU0uBAukywJNqf8LUfQ1NxhS+m6uxBwhdFqXGs2HsKW6okECDmu16tlEvtGDgRFzB9beHXsHBVw3TUBH1H3BC+WPioI6+XsNl5gxT2xkgstMdQsCHx93r5+Js/9d157poDJIwfIXIDv46fzj7291nNqmNZ3R/yWOj6f6jFOFom1vFNqPvYp/CuPy+BWD9IRPkB/dPK0DfCntKusuGnjrxOMUkdlBCyku0N1fTyUMSlvbSs5VghjZmVp6b78EbYMM0zcso/Cq03tAQnkor6uUdbUMAHJGNEj9uZGekyhVlr6Jaf02qHHX1VYJCZD0QihpmbeqzT9JI7h/WNvkZ+7fCtShIyP45WUv9ccyANNkVikZoAYyVJsZodIDTrMSIXdWFHTXMbnZtG/s8rzgEeItZvhkxt0ORfVn4wLeDFH0tNTn8Kt/4dNbZspcsiQ6wNaXORScDoTn9WUT+i8myFCGhXv9ZE9HLPmeJPWUqWoswq3ZIewwbssC49rLI5iG5puAlA5b/v3mKiLrho8jB5oxMl4qjXr6tW9tiFkAvw3WQPI/uU+dx99JgG+8LhW+Nn1Y4+IcRIJouxc6DqmoMs=
