language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=anotherlocallib.settings.test
script:
- python manage.py test --settings=anotherlocallib.settings.test
notifications:
  slack:
    secure: JpCZ6xfGLDTrrQKxt4qXn7zZU1gX+uU0C78uC/hI/mmxzI5oJOiyheHZg5qJwPfYXwCdi4em0vv6IhRhcYVMcoHZ+9vc2G22GYXsMD3/TNdwp85gRI/Ha7uwD2TB/xy8kHcJmySYG8PvNw8t/u81K0X6g/anS8B7c1Mx/Yv7E9Za3G99PUlrepMZQnlvaQFDr83paicKhAvmmDE6+LvTjOq4z1dKyzlkLJ0RMkt1NQ1sftO4aG9cAg/sQxMQbXvz8ZN1R8Y8y8sE/Itq3FIigBNAPzCaG929ggnvx2gzAt4TyUX78I9ZxColm4nv5NbgEccQmjw403zahIb10zi8f5ckyYHbskTgDDNP1VE6l0nM8WDmTzRaRFdGViaWdUsuH+fK74I2frfEp4KNpeh9kQ4v0OX533aZkrFWMNFZ6hhKd7kopLEdN37FZln9YMiKbE+czKUJusy4lutjnyHxP74pqpRxkdHeb98qGLDdP5g1k8zNOxuGUHvrJOF+twfYnTjUyTVfp5YyxjPdnfJLAbnJdJbX4+hdPLMgFtgmqbbjBgEEjICYfCsdpdcBCFiTqMDHN+4UZzgVmlaWwrj3Y+54rr5Ol/iTb4gO6txw/kNnbsXe8gE9oq7u5XdxnytUKG6u+ONjGKr8YnQCDlSHvivx7qT+B/u8lK1kJQJi19w=
deploy:
  provider: heroku
  api_key:
    secure: Icy4q/iowm+yRJ21bQZjNLg2ehKQj0DNhNI75NrcZVF5Nl4kbUyM2c7sw+p502gXT6kHOCHzOiS9PiKTiwHGpfnlVJJn/w3RaUJl9bGFRR2S0Vb3Efachsei5cIUPtp9etCZByx50wt1FWnxmikiSweW4qPMM1VTk6LoOkPyHlZ+ICYclbtG5xPb3owLVcZeK2y90WUHLzPe10Cy+G835A1/qfhOpxmRumZjLUM/sMiVlAlTaF3w2pacEz8m1nOOCIzjQzfTu7eJ4w3OA7YYHhoG9Pw/Tt1qHrkHKcp2NIC/6TooJSwtc/WwYXYDxX6zaX7CvteQjmnH9nQTJ5VBv5DYf70gFnpG7pSLjJH7Dbv1hGTP1ZTbqR2Z7fpoQb5PXYhXi3WIMM8wpauIS6RVXDNxcJVdYc6zm6DASO3zdCwG3tII5N6VmueKUIrDyCvhx2dbwsGRIf2U4drax1EYe2HlvB5u8cAENLy7E0mOjJxj72lDUW2AGmZF5KGXoHp99R5YahUYP9kB2eFH6a9vTvBeGcelrEkkvFue2aPCNbU4td22GBAPl9LpTRCvUVwKl13MGTIZQhHzs/2y1MMu1DxgzIepxGciR8WpjwPfrdATOPreDjlTvyGVPxG9qW3UOuhdtBnFUDQDviSE5k/6BJb73gp/0eV5LcsqHq9ztoM=

  app:
    master: anotherlocallib
    staging: anotherlocallib-staging
