language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=anotherlocallib.settings.test
script:
- python manage.py test --settings=anotherlocallib.settings.test
- flake8 .
notifications:
  slack:
    secure: RU9H0rdV0+dy6Jh9zDgXFVgedlJtjYZx+lBUZX6RiEFNQlMTPYAVlvOmHRi7b/NKzk34TLaQrOcXKPvO1PFzecMOKtU0uBAukywJNqf8LUfQ1NxhS+m6uxBwhdFqXGs2HsKW6okECDmu16tlEvtGDgRFzB9beHXsHBVw3TUBH1H3BC+WPioI6+XsNl5gxT2xkgstMdQsCHx93r5+Js/9d157poDJIwfIXIDv46fzj7291nNqmNZ3R/yWOj6f6jFOFom1vFNqPvYp/CuPy+BWD9IRPkB/dPK0DfCntKusuGnjrxOMUkdlBCyku0N1fTyUMSlvbSs5VghjZmVp6b78EbYMM0zcso/Cq03tAQnkor6uUdbUMAHJGNEj9uZGekyhVlr6Jaf02qHHX1VYJCZD0QihpmbeqzT9JI7h/WNvkZ+7fCtShIyP45WUv9ccyANNkVikZoAYyVJsZodIDTrMSIXdWFHTXMbnZtG/s8rzgEeItZvhkxt0ORfVn4wLeDFH0tNTn8Kt/4dNbZspcsiQ6wNaXORScDoTn9WUT+i8myFCGhXv9ZE9HLPmeJPWUqWoswq3ZIewwbssC49rLI5iG5puAlA5b/v3mKiLrho8jB5oxMl4qjXr6tW9tiFkAvw3WQPI/uU+dx99JgG+8LhW+Nn1Y4+IcRIJouxc6DqmoMs=
deploy:
  provider: heroku
  api_key:
    secure: EMNU2DHz8Cj2VBacUQG4HvR2gmGXqFTn04teEFsLkGhx6TZKi58atDfUShOKeoOp/f50XluzAz3CQtcMAmaFrqCO/ARiwo+xGvsxGCBr3kGDuJXhY5rgsyiOW43KtpP4/5ZZlRn6RqB6ebmpjpinF4vhGegfeb9GSSymKXR3E/2H9xH43JkkAdOAATMBPIcfgKn6KruLRy4X9eVDFYssWQw6uGfNbyUic6+GHPNbLOWg5tb0ipZa+1UZpi/831s+BRR9Erkd14WUQvYjqaAMggiXBtwnaSjbKj/ZGoGBvswNIYOo+dm0TVIUJWCt5JNdYEKZEcmA/uRR6VzmRcorOmDibgOIMBKiogkZm0SFeS770h9sTJBOX7M8rMCfssn7ylJrQLnv3FzU5MeZnbltTtX2HPRa9OdwEaIniA5yw5KJzH21T0ZpGbiOdqm/nHTdltPlyIYDwu4SwyLLjBwHDwKxgBblWST5aagQMVrt2tV+rhnxARgfki1qYSbEoN3WDMHJjrv7GVZyxT8niRsWRn08JKWyWD+XxwowS4vcwwnYCthgcyqrbJxm1wRmlJOzYrWJEoX3GJkPCEQMDy0mqM5a2jlM8+XMgX54AReu88h7/HNKZKUNz/CKD2gK////FKCpPXq/7lbNfW9RcDS8EmCxjEBYajv4IJGQUdrUSQo=
  app:
    master: anotherlocallib
    staging: anotherlocallib-staging
