language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=anotherlocallib.settings.test
script:
- python manage.py test --settings=anotherlocallib.settings.test
notifications:
  slack:
    secure: RU9H0rdV0+dy6Jh9zDgXFVgedlJtjYZx+lBUZX6RiEFNQlMTPYAVlvOmHRi7b/NKzk34TLaQrOcXKPvO1PFzecMOKtU0uBAukywJNqf8LUfQ1NxhS+m6uxBwhdFqXGs2HsKW6okECDmu16tlEvtGDgRFzB9beHXsHBVw3TUBH1H3BC+WPioI6+XsNl5gxT2xkgstMdQsCHx93r5+Js/9d157poDJIwfIXIDv46fzj7291nNqmNZ3R/yWOj6f6jFOFom1vFNqPvYp/CuPy+BWD9IRPkB/dPK0DfCntKusuGnjrxOMUkdlBCyku0N1fTyUMSlvbSs5VghjZmVp6b78EbYMM0zcso/Cq03tAQnkor6uUdbUMAHJGNEj9uZGekyhVlr6Jaf02qHHX1VYJCZD0QihpmbeqzT9JI7h/WNvkZ+7fCtShIyP45WUv9ccyANNkVikZoAYyVJsZodIDTrMSIXdWFHTXMbnZtG/s8rzgEeItZvhkxt0ORfVn4wLeDFH0tNTn8Kt/4dNbZspcsiQ6wNaXORScDoTn9WUT+i8myFCGhXv9ZE9HLPmeJPWUqWoswq3ZIewwbssC49rLI5iG5puAlA5b/v3mKiLrho8jB5oxMl4qjXr6tW9tiFkAvw3WQPI/uU+dx99JgG+8LhW+Nn1Y4+IcRIJouxc6DqmoMs=
deploy:
  provider: heroku
  api_key:
    secure: N5qEmtsJZf8CbZHb7ex/BxONIJfo7UozlFZHuMSjKuSmWx+T1c8CqEwieXrf02rNK9aJiInPw7VOIX+oONpzYYEz/pRo45warP8pZuAc2AGnbploW4b52s7+/NQ1+qpdTb2kMTXxyn0MFNnlHcMkCM531iBisjwJnzFtL3P28ooz8DdoQBTro+bsXL/Pli2Tj+pY7IDZD8zTSxiDLb9xuarLCq7jjAEqjT0BqCfizLH5tJOkieFr2y+mwCxpCRt3XQseNYLIhs/IouQE9HYKAgZ+0TEusfy/gNGimz8i81gXc9ccuKTzWZkz8a4fL//0A/iH4kqVIhp1a0bjhSd+SrqtmWRRqOQUJ9ppZx/NuFnSDh7wjXc8LP09lUgOEg9LXdoLoSDH8TUqzt/xM1b3kgzngy7rziUeNdYWloFB736zGkXgoOf8hzFAt1Gz1vs5203ZpsUYi5vDHMXiBI6awH2UFSR7z/h+vXMi0WiGGp7hEQA7iFRcCV5xqLoTMjNtISxbkVLRMf2GdUW9GFwzG4+Omxl5OlcA6V5m4iXLpJCO5PONBYzawZLBsPwmJJ9uDhikwA0C7kMFcab4rVuxQfubtm2m7GIJHxNcSfEocMc3Yjhbz9OzK19TxTnOE6gYGLLDu1GHSvI08uYjobeNAgSGYuQFNSAqkbhmXYod/zI=
  app:
    master: anotherlocallib
    staging: anotherlocallib-staging
